### ISSUE TITLE
about Permission denied (publickey). fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by ChenReason** [vichid/Selene#1]
Hi friend,it's so pity when I was cloning the repository the error message showed "Permission denied (publickey).fatal: Could not read from remote repository." I cannot solve it so I  want some help from you ,thank you:)

**Comment by vichid** [comment]
You must fork it or download a copy of this project to use it, for submitting any change to this project you can send a pull request ;)

**Comment by ChenReason** [comment]
Ok,I got it!Thank you very much:)

**Comment by RaviH** [comment]
Also, you can do `git clone https://github.com/vichid/Selene.git`
