### ISSUE TITLE
Would like to know how to setup correct links for the round icons on the top right and what they stand for.

### ISSUE THREAD

**Issue by RaviH** [vichid/Selene#2]
Hi,

I know one stands for bitbucket, another for github, another for stackoverflow. But it would be very helpful to know how I can modify them so that they link to correct places. Moreover, I don't know what each of them stand for. So it would be super awesome that when I hover over them that they say "You github", "Your codepen" etc...

So in summary:

a. hover with more informative verbiage
b. README.md on how to provide correct links for them. It would be awesome if you provide a config.js that users can modify to provide correct links.

Thank you for the beautiful work!

**Comment by vichid** [comment]
I see what you mean, I would work on it when I have more time, thanks for the feedback! :+1:

**Comment by vichid** [comment]
I hope now it's clearer.
