### ISSUE TITLE
Headers cause an extra line visually in Selene whereas that extra line does not appear in the preview pane.

### ISSUE THREAD

**Issue by RaviH** [vichid/Selene#4]
Hello,

I am seeing an issue with `H6` header. Possibly with other sizes too. ![Here's a screen shot](/home/ravi/Pictures/H6_Header_issue.png)

And here's the actual HTML: 

```
<p>This means the <code>request.status_code</code> is incorrect when accessed in the          
<code>after_request</code> method.</p>

<h6 id="workaround">Workaround:</h6>

<p>To circumnavigate the issue I used <code>Bottle's Plugin</code> concept like so:</p>

<pre><code>from bottle import Bottle, run, response, HTTPResponse
```

**Comment by vichid** [comment]
I can't reproduce the issue you're talking about. It should be working ok if you don't do any modification ;). Try to upload again the image if that helps, but for me it's ok.

**Comment by RaviH** [comment]
http://javawithravi.com/2014/11/10/bottle-after_request-hook-does-not-provide-correct-status_code/

Notice the space after 'Issue' and 'Workaround'
