### ISSUE TITLE
Customization Documentation?

### ISSUE THREAD

**Issue by the4ndy** [vichid/Selene#7]
Is there any documentation on how to get started customizing the theme? Perhaps adding a background picture to the header? Changing the default color? Anything at all would be greatly appreciated. I am new to Ghost overall but if you point me in the right direction I am fairly competent and hopefully could contribute some How To's based on my discovery. Thanks

**Comment by vichid** [comment]
Ghost itself allows you to upload an image for your header. 

If you want to change some of the colors I'm using you have to modify [this file](https://github.com/vichid/Selene/blob/master/assets/sass/modules/_colors.scss) and then re-run grunt.
